[build]
  functions = "my_functions"
  publish = "frontend"  # Byt ut "frontend" med namnet på din mapp för statiska filer

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  functions = "my_functions"
